PREFIX edm:     <http://www.europeana.eu/schemas/edm/>
PREFIX ebucore: <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#>

SELECT ?item ?url ?mime ?width ?height ?bytes
WHERE {
  ?agg edm:aggregatedCHO ?item ;
       edm:isShownBy ?url .
  OPTIONAL { ?url ebucore:hasMimeType ?mime }
  OPTIONAL { ?url ebucore:width ?width }
  OPTIONAL { ?url ebucore:height ?height }
  OPTIONAL { ?url ebucore:fileByteSize ?bytes }
}