PREFIX edm: <http://www.europeana.eu/schemas/edm/>

SELECT ?item ?rights ?dataProvider ?provider ?country ?completeness
WHERE {
  ?agg edm:aggregatedCHO ?item ;
       edm:rights ?rights ;
       edm:dataProvider ?dataProvider ;
       edm:provider ?provider .
  ?eAgg edm:aggregatedCHO ?item ;
        edm:country ?country ;
        edm:completeness ?completeness .
  ?eAgg a edm:EuropeanaAggregation .
}
