PREFIX edm:    <http://www.europeana.eu/schemas/edm/>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>
PREFIX rdaGr2: <http://rdvocab.info/ElementsGr2/>
PREFIX owl:    <http://www.w3.org/2002/07/owl#>

SELECT ?agent ?name ?lang ?birth ?death ?profession ?wikidata
WHERE {
  ?agent a edm:Agent ;
         skos:prefLabel ?name .
  BIND(LANG(?name) AS ?lang)
  OPTIONAL { ?agent rdaGr2:dateOfBirth ?birth }
  OPTIONAL { ?agent rdaGr2:dateOfDeath ?death }
  OPTIONAL { ?agent rdaGr2:professionOrOccupation ?profession }
  OPTIONAL {
    ?agent owl:sameAs ?wikidata .
    FILTER(STRSTARTS(STR(?wikidata), "http://www.wikidata.org/entity/"))
  }
}
