PREFIX edm:      <http://www.europeana.eu/schemas/edm/>
PREFIX skos:     <http://www.w3.org/2004/02/skos/core#>
PREFIX wgs84_pos:<http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX owl:      <http://www.w3.org/2002/07/owl#>

SELECT ?place ?name ?lang ?lat ?lon ?wikidata
WHERE {
  ?place a edm:Place ;
         skos:prefLabel ?name .
  BIND(LANG(?name) AS ?lang)
  OPTIONAL { ?place wgs84_pos:lat ?lat }
  OPTIONAL { ?place wgs84_pos:long ?lon }
  OPTIONAL {
    ?place owl:sameAs ?wikidata .
    FILTER(STRSTARTS(STR(?wikidata), "http://www.wikidata.org/entity/"))
  }
}
